### ISSUE TITLE
in the pressure test,cpu usage suddenly fall for a moment，it leads to that requests were time out  

### ISSUE THREAD

**Issue by naah69** [Thriftpy/gunicorn_thrift#57]
i use this to create a service that provide RPC interface.
but when it was in pressure test,
cpu usage suddenly falled for a moment(about 10 seconds),then lots of requests were time out.
then all of these were back to normal.but after several minutes.it repeated again.
i use gevent model and 6 workers.
can you help me ?

**Comment by wooparadog** [comment]
it seems that there's a blockage in your app. You can use the following
tools to detect it:

* py-spy to print out thread stacks when your app is blocking.
* or use pystack to print out your greenlet stacks while blocking.
* or use strace and lsof to profile your app in realtime.

Once the blocking component is found, try google its compatibility with
gevent

**Comment by wooparadog** [comment]
Closing for now, welcome to reopen
