### ISSUE TITLE
线上偶现请求时间过长问题

### ISSUE THREAD

**Issue by sunzhy** [Thriftpy/gunicorn_thrift#67]
项目使用 gunicorn_thrift + thriftpy2，接口正常请求时间400ms左右，但是持续请求测试时，客户端打印请求时间发现，偶尔会出现十几秒甚至几十秒的请求时间（我timeout设置比较大）。接口本身逻辑简单且服务端（业务代码）打印请求时间正常。线上请求量不算大，QPS最高也就300r/s
不知道你们有没有遇到过类似问题......

**Comment by ethe** [comment]
How to reproduce it?

**Comment by gladuo** [comment]
> How to reproduce it?

I have same problems
