### ISSUE TITLE
Issue of gunicorn version

### ISSUE THREAD

**Issue by xyg-coder** [Thriftpy/gunicorn_thrift#68]
I would recommend changing the requirement gunicorn version to `19.9.0`. Because older version has issue: https://github.com/benoitc/gunicorn/issues/1822
Later version has `six` import problem.

**Comment by ethe** [comment]
I will look it later, could you please give bits of help?

**Comment by xyg-coder** [comment]
Thanks ethe. I would like to. I will ask for a merge tomorrow or next week.

**Comment by ethe** [comment]
Closed.
