### ISSUE TITLE
Configure worker number

### ISSUE THREAD

**Issue by xyg-coder** [Thriftpy/gunicorn_thrift#70]
Hi. Is there some way to do more grained configuration in gunicorn_thrift just like gunicorn? E.g. worker number or thread number.

**Comment by ethe** [comment]
Most of the configuration of Gunicorn such as worker number can be used in gunicorn_thrift, if you have some problem to use it, please post here, thank you.

**Comment by xyg-coder** [comment]
Yes it works. Thanks for answering ethe.
