### ISSUE TITLE
Is this repo alive?

### ISSUE THREAD

**Issue by Catelemmon** [Thriftpy/gunicorn_thrift#71]
when I use `gunicorn_thrift -c gunicorn.py pythriftServer:app` to launch my thrifypy2 app, import error occured like follow
```
(monitor) ➜  pythriftCoco gunicorn_thrift -c gunicorn.py pythriftServer:app
Traceback (most recent call last):
  File "/home/cicada/.pyenv/versions/monitor/bin/gunicorn_thrift", line 7, in <module>
    from gunicorn_thrift.thriftapp import run
  File "/home/cicada/.pyenv/versions/3.6.5/envs/monitor/lib/python3.6/site-packages/gunicorn_thrift/thriftapp.py", line 11, in <module>
    from . import config
  File "/home/cicada/.pyenv/versions/3.6.5/envs/monitor/lib/python3.6/site-packages/gunicorn_thrift/config.py", line 4, in <module>
    from gunicorn import six
ImportError: cannot import name 'six'
```
maybe gunicorn_thrift version is not matched with gunicorn

**Comment by ethe** [comment]
Do not panic, I am checking it.

**Comment by ethe** [comment]
Sorry, I can not reproduce your problem, could you please tell me which version of Gunicorn you are using now?

**Comment by ethe** [comment]
Please upgrade gunicorn_thrift to 0.2.25

**Comment by cicada-lewis** [comment]
I have tried this and reproduced it. I have installed gunicorn 20.0.4 before gunicorn_thrift. In gunicorn v20.0.4, `from gunicorn import six` will causes import error, and when I install gunicorn_thrift, pip didn't remind me to install  gunicorn v19.9.0, please check this in `setup.py`.

**Comment by cicada-lewis** [comment]
And I have an another question, do you have plan to support `eventlet`?

**Comment by Catelemmon** [comment]
very thx~You are so quick, I guess there is no 996 in eleme, hhhhhh

**Comment by ethe** [comment]
Gunicorn does not support asyncio very well, so the answer may be no, however, thriftpy2 has already supported asyncio, maybe we can integrate it to another ASGI server like uvicorn.

**Comment by wooparadog** [comment]
Did some testing. I've successfully installed the corrected gunicorn version, more info is needed if dependencies are indeed broken.

![image](https://user-images.githubusercontent.com/1130984/70295306-82764d80-1821-11ea-893a-c4fde6ac211c.png)

**Comment by cicada-lewis** [comment]
This error only occured in version 0.2.24, @ethe has fixed this error last night, gunicorn_thrift has bumped to 0.2.25, you can reproduce that by `pip install gunicorn_thrift==0.2.4`, pip won't check the correct gunicorn version like follow.
![gunicorn_thrift-0 2 24](https://user-images.githubusercontent.com/16452037/70300233-f15ba280-1831-11ea-874d-ba21d98782f0.png)
but in 0.2.25, everything is ok.
![gunicorn_thrift-0 2 25](https://user-images.githubusercontent.com/16452037/70300422-721a9e80-1832-11ea-8430-fe748cb09439.png)

**Comment by cicada-lewis** [comment]
And very thx for fixing that @ethe, sure also about you @wooparadog.

> Gunicorn does not support asyncio very well, so the answer may be no, however, thriftpy2 has already supported asyncio, maybe we can integrate it to another ASGI server like uvicorn.

emmm... In fact I want to asign [eventlet](https://github.com/eventlet/eventlet) to worker_class not asyncio, but thriftpy2 and gunicorn_thrift don't seem to support it. When I try to use eventlet as worker_class to patch_all, `eventlet.socket` is not supported. But I need eventlet to patch another libaray. I am searching the most optimal method.

**Comment by ethe** [comment]
We do not have any plan to support `eventlet`, all support about concurrent will base on `asyncio`.

**Comment by cicada-lewis** [comment]
Ok, I got it, thx again, it's a cool repo. I am pleasent to use it in my  business code with some hack.
